# Flare Database

Add Bob Leamon's flare database to the neutral density database. 

Classify each time interval as flare/no-flare and flare clase.

In [57]:
#print all output in a cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [86]:
# import stuff
import os
import pandas as pd
import scipy.io as sio

# save data 
sdat = True
sdir = 'C:/Users/krmurph1/OneDrive/SatDrag_RF'

# Read in the satellite drag database
#fn = 'D:\\data\\VL_sdrag\\satdrag_database_zlib.hdf5'
fn = 'D:\\data\\SatDensities\\satdrag_database_grace_B.hdf5'
sd_dat = pd.read_hdf(fn)

In [59]:
# Read in Flare Database
# and convert to DataFrame

fl_dat = sio.readsav("d:/data/flare list/GOES_FLARE_RECORDS_1975_2024.sav")
d = dict()
for key in fl_dat['goes'].dtype.names:                             
    v = fl_dat['goes'][key]            
    try:                                                                  
        v = v.byteswap().newbyteorder()
    except ValueError:
        pass
    d[key] = v

fl_df = pd.DataFrame(d)

In [87]:
# loop through the flares and set
# flags in the satellite drag database
# for the different times

sd_dat['flare'] = -1
sd_dat['flare class'] = -1
sd_dat['flare magnitude'] = -1
sd_dat['flare peak energy'] = -1
sd_dat['flare index'] = -1


for index, row in fl_df.iterrows():

    st_time = pd.to_datetime(row['START_TIME'].decode())
    if st_time < sd_dat['DateTime'].min():
        continue

    try:        
        en_time = pd.to_datetime(row['END_TIME'].decode())
    except:
        print(f"Times: {row['START_TIME'].decode()} - {row['END_TIME'].decode()}")
        continue       

    

    fl_t = (sd_dat['DateTime'] >= st_time) & (sd_dat['DateTime'] <= en_time) 


    
    sd_dat.loc[fl_t,'flare'] = 1
    try:
        sd_dat.loc[fl_t,'flare class'] = row['CLASS'].decode()
    except:
        sd_dat.loc[fl_t,'flare class'] = row['CLASS']
    sd_dat.loc[fl_t,'flare magnitude'] = row['FLARE_MAGNITUDE']
    sd_dat.loc[fl_t,'flare peak energy'] = row['PEAK_ENERGY']
    sd_dat.loc[fl_t,'flare index'] = index

In [89]:
b = (sd_dat['flare'] > 0) & (sd_dat[s])
sd_dat[b].tail(20)

,DateTime,DateTime_omni,B,Bx_GSEGSM,By_GSE,Bz_GSE,By_GSM,Bz_GSM,Vsw,Vx_GSE,...,NumPts,NuminBinThrusters,AveDragCoef,storm,storm phase,flare,flare class,flare magnitude,flare peak energy,flare index
1042903,2012-06-30 04:35:00,2012-06-30 04:35:00,10.80,9.57,-4.79,1.35,-4.71,1.60,408.1,-401.1,...,7.0,0.0,3.014,-1,-1,1,C,10.0,0.00013,68531
1042904,2012-06-30 04:40:00,2012-06-30 04:40:00,10.75,9.78,-4.12,1.40,-4.04,1.63,408.9,-399.6,...,4.0,4.0,2.922,-1,-1,1,C,10.0,0.00013,68531
1042949,2012-06-30 08:25:00,2012-06-30 08:25:00,7.35,7.15,0.95,-0.99,0.72,-1.16,476.3,-475.8,...,2.0,2.0,3.237,-1,-1,1,C,4.4,0.00250,68532
1042950,2012-06-30 08:30:00,2012-06-30 08:30:00,8.05,7.09,-3.48,-0.55,-3.52,0.19,479.4,-478.8,...,3.0,0.0,3.055,-1,-1,1,C,4.4,0.00250,68532
1042951,2012-06-30 08:35:00,2012-06-30 08:35:00,9.12,7.85,-4.01,-0.40,-4.01,0.46,486.0,-485.3,...,4.0,4.0,2.948,-1,-1,1,C,4.4,0.00250,68532
1042966,2012-06-30 09:50:00,2012-06-30 09:50:00,10.45,-0.83,-1.90,-9.49,-4.11,-8.76,504.3,-502.5,...,1.0,0.0,3.399,-1,-1,1,C,1.6,0.00049,68533
1042967,2012-06-30 09:55:00,2012-06-30 09:55:00,11.30,-0.80,3.32,-9.13,1.03,-9.67,511.1,-508.8,...,2.0,0.0,3.336,-1,-1,1,C,1.6,0.00049,68533
1042970,2012-06-30 10:10:00,2012-06-30 10:10:00,11.65,6.73,-7.16,-0.70,-7.12,1.06,544.2,-542.6,...,3.0,0.0,2.926,-1,-1,1,B,8.5,0.00024,68534
1042971,2012-06-30 10:15:00,2012-06-30 10:15:00,12.56,7.27,-7.60,-5.42,-8.70,-3.39,529.8,-527.1,...,5.0,5.0,2.861,-1,-1,1,B,8.5,0.00024,68534
1042978,2012-06-30 10:50:00,2012-06-30 10:50:00,12.03,7.90,-7.70,-2.34,-8.04,-0.36,572.9,-569.8,...,5.0,0.0,3.016,-1,-1,1,C,2.7,0.00150,68535
1042979,2012-06-30 10:55:00,2012-06-30 10:55:00,12.40,9.62,-4.97,-5.24,-6.12,-3.84,576.5,-569.1,...,1.0,0.0,2.917,-1,-1,1,C,2.7,0.00150,68535
1042980,2012-06-30 11:00:00,2012-06-30 11:00:00,11.86,9.43,-6.38,-1.03,-6.43,0.60,571.0,-565.0,...,8.0,0.0,2.890,-1,-1,1,C,2.7,0.00150,68535
1043002,2012-06-30 12:50:00,2012-06-30 12:50:00,11.56,6.97,-8.23,0.32,-7.93,2.25,598.1,-587.2,...,9.0,8.0,3.081,-1,-1,1,M,10.0,0.00170,68536
1043041,2012-06-30 16:05:00,2012-06-30 16:05:00,10.30,6.38,-3.70,3.67,-3.28,4.06,601.9,-593.6,...,8.0,0.0,3.422,-1,-1,1,C,1.3,0.00170,68537
1043042,2012-06-30 16:10:00,2012-06-30 16:10:00,9.48,5.12,-3.21,4.42,-2.73,4.73,612.5,-604.4,...,2.0,0.0,3.324,-1,-1,1,C,1.3,0.00170,68537
1043043,2012-06-30 16:15:00,2012-06-30 16:15:00,8.85,2.29,-3.03,7.22,-2.27,7.50,615.9,-608.6,...,9.0,0.0,3.152,-1,-1,1,C,1.3,0.00170,68537
1043044,2012-06-30 16:20:00,2012-06-30 16:20:00,8.65,5.21,1.24,6.66,1.89,6.51,NaN,NaN,...,10.0,0.0,3.038,-1,-1,1,C,1.3,0.00170,68537
1043045,2012-06-30 16:25:00,2012-06-30 16:25:00,9.59,4.03,1.79,3.45,2.10,3.27,612.5,-599.9,...,3.0,3.0,2.939,-1,-1,1,C,1.3,0.00170,68537
1043070,2012-06-30 18:30:00,2012-06-30 18:30:00,6.11,5.77,0.92,-1.70,0.94,-1.69,641.7,-639.9,...,5.0,0.0,3.288,-1,-1,1,M,1.6,0.00330,68538
1043105,2012-06-30 21:25:00,2012-06-30 21:25:00,6.97,3.59,-2.30,-4.16,-1.84,-4.38,631.1,-628.1,...,4.0,0.0,3.128,-1,-1,1,C,1.4,0.00030,68539

## Save data

In [91]:
fn = 'D:\\data\\SatDensities\\satdrag_database_grace_B_flare'
sd_dat.to_hdf(fn+'.hdf5',key='database', mode='w', format='fixed', complevel=9)

C:\Users\krmurph1\AppData\Local\Temp\ipykernel_27112\2235708688.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block3_values] [items->Index(['flare class'], dtype='object')]

  sd_dat.to_hdf(fn+'.hdf5',key='database', mode='w', format='fixed', complevel=9)

In [101]:
sd_dat.columns

Index(['DateTime', 'DateTime_omni', 'B', 'Bx_GSEGSM', 'By_GSE', 'Bz_GSE',
       'By_GSM', 'Bz_GSM', 'Vsw', 'Vx_GSE', 'Vy_GSE', 'Vz_GSE', 'Prho', 'Tp',
       'dynP', 'Esw', 'AE', 'AL', 'AU', 'SYM_D index', 'SYM_H index',
       'ASY_D index', 'ASY_H index', 'PC index', 'Goes Proton flux (>10 MeV)',
       'Goes Proton flux (>30 MeV)', 'Goes Proton flux (>60 MeV)',
       'DateTime_fism2', '225_00', '600_01', '1300_02', '2500_03', '5100_04',
       '11250_05', '18950_06', '25700_07', '30500_08', '43000_09', '59500_10',
       '72400_11', '72400_12', '85550_13', '85550_14', '85550_15', '94400_16',
       '94400_17', '94400_18', '98100_19', '100700_20', '103850_21',
       '113000_22', 'DateTime_si', 'F10', 'F81', 'S10', 'S81c', 'M10', 'M81c',
       'Y10', 'Y81c', 'DateTime_gr', 'CenterLat', 'SatLat', 'SatLon',
       'SatHeight', 'SatLT', 'SatDipoleLat', 'SatMagLon', 'SatMagLT',
       'SatDensity', '400kmDensity', '410kmDensity', 'NRLMSISe00atSat',
       'DenUncertainty', 'NumPts', 'NuminBinThrusters', 'AveDragCoef', 'storm',
       'storm phase', 'flare', 'flare class', 'flare magnitude',
       'flare peak energy', 'flare index'],
      dtype='object')

In [102]:
sd_dat.to_csv(fn+'.csv.gz',na_rep='NaN')

In [100]:
sd_dat.iloc[:,30:60].head()

,1300_02,2500_03,5100_04,11250_05,18950_06,25700_07,30500_08,43000_09,59500_10,72400_11,...,113000_22,DateTime_si,F10,F81,S10,S81c,M10,M81c,Y10,Y81c
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN